version: '3.8'

services:
  app:
    container_name: orm-demo
    build: .
    stdin_open: true  # Etkileşimli girdi için
    tty: true         # Terminali açmak için
    image: orm-image
    networks:
      - external-api   # Özel ağa bağlanma
    environment:
      - JDBC_DATABASE_URL=jdbc:mysql://mysql:3306/school_db  # MySQL servisi adıyla bağlanma
      - JDBC_DATABASE_USERNAME=root
      - JDBC_DATABASE_PASSWORD=12345
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql-orm-demo
    restart: always
    networks:
      - external-api   # Özel ağa bağlanma
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: school_db
    ports:
      - "3308:3306"    # Dışarıya 3308 portunu açma

networks:
  external-api:       # Özel ağ tanımı