version: '3'

services:

  docker-mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: 'school_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3306:3306'
    networks:
      - orm-network

  app:
    image:  ahmeteminsaglik/jpa-hibernate-console
    depends_on:
      - docker-mysql
    networks:
        - orm-network


networks:
  orm-network:
    driver: bridge
