version: '3.8'

services:
  app:
    container_name: orm-demo
    build: .
    stdin_open: true  # Etkileşimli girdi için
    tty: true         # Terminali açmak için
    image:  orm-image
    network_mode: default
    environment:
      - JDBC_DATABASE_URL=jdbc:mysql://mysql:3307/school_db
      - JDBC_DATABASE_USERNAME=root
      - JDBC_DATABASE_PASSWORD=
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3307/school_db
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    network_mode: default
    container_name: mysql-orm-demo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: school_db
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3307:3306"
      # version: '3.8'

# services:
#   app:
#     build: .
#     stdin_open: true  # Etkileşimli girdi için
#     tty: true         # Terminali açmak için
#     environment:
#       - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/school_db
#       - SPRING_DATASOURCE_USERNAME=root
#       - SPRING_DATASOURCE_PASSWORD=
#     depends_on:
#       - mysql

#   mysql:
#     image: mysql:latest
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD:
#       MYSQL_DATABASE: school_db
#     ports:
#       - "3307:3306"
#       # version: '3.8'

# # services:
# #   app:
# #     build: .
# #     environment:
# #       - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/school_db
# #       - SPRING_DATASOURCE_USERNAME=root
# #       - SPRING_DATASOURCE_PASSWORD=
# #     depends_on:
# #       - mysql

# #   mysql:
# #     image: mysql:latest
# #     restart: always
# #     environment:
# #       MYSQL_ROOT_PASSWORD:   # Root kullanıcısı için şifreyi ayarlayın
# #       MYSQL_DATABASE: school_db
# #     ports:
# #       - "3307:3306"